# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Van Le — Web developer based in London"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vann.io" # the base hostname & protocol for your site
twitter_username: vannio
github_username: vannio
linkedin_username: vannio

# Build settings
markdown: kramdown
exclude:
    - node_modules
    - Gemfile
    - Gemfile.lock
    - gulpfile.js
    - package.json
    - README.md
